FROM node:16.16.0
LABEL org.opencontainers.image.authors="Beken Sarsenbaev <sbeken6@gmail.com>"
WORKDIR /ais_freedom
COPY build/ ./
COPY package*.json ./
COPY nodemon.json ./
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  ca-certificates fonts-liberation libappindicator3-1 libasound2 \
  libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
  libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 \
  libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
  libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 \
  libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils \
  libdbus-glib-1-2 \
  && rm -rf /var/lib/apt/lists/*
RUN npm install --location=global npm
RUN npm install --location=global nodemon
RUN npm install
EXPOSE 3000
