version: "3"

services:
  db:
    image: ais_freedom/mysql

    container_name: db

    ports:
      - 6033:3306

  server:
    image: ais_freedom/server

    container_name: server

    environment:
      NODE_ENV: development

    volumes:
      - "../server/build:/ais_freedom"
      - "../server/package.json:/ais_freedom/package.json"

    entrypoint: ["npm", "run", "start:dev"]

    ports:
      - 8080:3000

    links:
      - db

    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin

    container_name: pma

    links:
      - db

    environment:
      PMA_HOST: db

      PMA_PORT: 3306

      PMA_ARBITRARY: 1

    restart: always

    ports:
      - 8082:80

volumes:
  dbdata:
